import { DEFAULT_STATE, clone, escapeHtml as h } from './core/state.js';
import { loadState, saveState as persistState, loadSettings, saveSettings } from './core/storage.js';
import { mutateMetrics as applyMetricDelta, addDecision as recordDecision } from './core/metrics.js';
import { tone as playTone } from './core/audio.js';
import { applySettings } from './core/accessibility.js';
import { addLedger as recordLedger, renderLedger as drawLedger } from './core/ledger.js';
import { createRouter } from './core/router.js';
import { CHAPTERS } from './data/game-data.js';
import { monitorTile, metric } from './components/hud.js';
import { setChapter as updateChapter, chapterIntro as drawChapterIntro } from './components/progress.js';
import { abstraction as drawAbstraction } from './components/abstraction.js';
import { bindDialogs } from './components/dialogs.js';
import { createIntroRoutes } from './scenes/intro.js';
import { createMiningRoutes } from './scenes/mining.js';
import { createFactoryRoutes } from './scenes/factory.js';
import { createDatacenterRoutes } from './scenes/datacenter.js';
import { createDataRoutes } from './scenes/data.js';
import { createAnnotationRoutes } from './scenes/annotation.js';
import { createTrainingRoutes } from './scenes/training.js';
import { createEvaluationRoutes } from './scenes/evaluation.js';
import { createDeploymentRoutes } from './scenes/deployment.js';
import { createEndingRoutes } from './scenes/ending.js';

const $=(sel,root=document)=>root.querySelector(sel);const $$=(sel,root=document)=>[...root.querySelectorAll(sel)];
const sceneEl=$('#scene'), progressEl=$('#journeyProgress'), progressFill=$('#progressFill'), chapterLabel=$('#chapterLabel'), chapterTitle=$('#chapterTitle'), ledgerBtn=$('#ledgerBtn'), ledgerDialog=$('#ledgerDialog'), ledgerContent=$('#ledgerContent'), settingsDialog=$('#settingsDialog'), confirmResetDialog=$('#confirmResetDialog'), persistentFooter=$('#persistentFooter');
let currentState=loadState(DEFAULT_STATE), currentSettings=loadSettings();
const proxy=(getter,setter)=>new Proxy({}, {get:(_,p)=>getter()[p],set:(_,p,v)=>{setter(p,v);return true;},ownKeys:()=>Reflect.ownKeys(getter()),getOwnPropertyDescriptor:()=>({enumerable:true,configurable:true})});
const state=proxy(()=>currentState,(p,v)=>currentState[p]=v);const settings=proxy(()=>currentSettings,(p,v)=>currentSettings[p]=v);
let router;
const saveState=()=>persistState(currentState);const mutateMetrics=delta=>{applyMetricDelta(currentState,delta);saveState();};const addDecision=(id,label,effectText,delta={})=>{recordDecision(currentState,id,label,effectText,delta);saveState();};const addLedger=(chapter,human,work,system,details='')=>{recordLedger(currentState,chapter,human,work,system,details);saveState();drawLedger(currentState,CHAPTERS,ledgerContent);};const renderLedger=()=>drawLedger(currentState,CHAPTERS,ledgerContent);const tone=(freq=440,duration=.06,type='sine')=>playTone(currentSettings,freq,duration,type);
const ctx={$, $$, state, settings, h, chapters:CHAPTERS, progressEl,progressFill,chapterLabel,chapterTitle,ledgerBtn,ledgerDialog,ledgerContent,settingsDialog,confirmResetDialog,persistentFooter,saveState,mutateMetrics,addDecision,addLedger,renderLedger,tone,monitorTile,metric};
router=createRouter({stateProxy:state,settingsProxy:settings,sceneEl,save:saveState,tone,renderLedger});Object.assign(ctx,{html:router.html,bind:router.bind,go:router.go,render:router.render});ctx.setChapter=index=>updateChapter(ctx,index);ctx.chapterIntro=(index,title,subtitle,next)=>drawChapterIntro(ctx,index,title,subtitle,next);ctx.abstraction=(humans,word,line,next)=>drawAbstraction(ctx,humans,word,line,next);
ctx.resetGame=(goIntro=false)=>{currentState=clone(DEFAULT_STATE);saveState();ledgerDialog.close();settingsDialog.close();confirmResetDialog.close();if(goIntro)router.go('intro');else router.render();};
[createIntroRoutes,createMiningRoutes,createFactoryRoutes,createDatacenterRoutes,createDataRoutes,createAnnotationRoutes,createTrainingRoutes,createEvaluationRoutes,createDeploymentRoutes,createEndingRoutes].forEach(factory=>router.register(factory(ctx)));
bindDialogs(ctx);
['reduceMotion','highContrast','largeText','soundOn'].forEach(id=>$('#'+id).addEventListener('change',event=>{currentSettings[id]=event.target.checked;saveSettings(currentSettings);applySettings(currentSettings);}));
applySettings(currentSettings);router.render();
