import { ANNOTATION_TASKS, ANNOTATION_LABELS } from '../data/game-data.js';
export function createAnnotationRoutes(ctx){
  const $=ctx.$, state=ctx.state;
  const {setChapter,chapterIntro,html,go,bind,saveState,mutateMetrics,addDecision,addLedger}=ctx;
  const abstraction=(humans,word,line,next)=>ctx.abstraction(humans,word,line,next);
  function ch5Intro(){chapterIntro(4,'','','annotationIntro');}
  function annotationIntro(){setChapter(4);html(`<div class="annotation-shell"><div class="annotation-head"><strong>منصة «مهمة»</strong><span>مشروع تصنيف بيانات</span></div><div class="annotation-body"><span class="eyebrow" style="color:#237b67">عاملة تصنيف بيانات</span><h1 style="margin:6px 0 12px">مرحبًا أماني.</h1><div class="reality-note" style="color:#314050;background:#f6f8fa"><strong>ما وظيفة هذا العمل؟</strong> ستقرئين أمثلة قصيرة وتضعين لكل منها تصنيفًا. هذه القرارات لا تبدو جزءًا من «الذكاء الاصطناعي» للمستخدم، لكنها قد تدخل في إعداد بيانات أو تقييمات تستخدمها فرق التطوير.</div><p>صنّفي المحتوى بحسب الفئة الأقرب. الدفع مقابل المهام المقبولة. يجب الحفاظ على دقة مرتفعة، والسرعة تؤثر في إتاحة مهام إضافية.</p><div class="annotation-stats"><span>الدفع: لكل مهمة مقبولة</span><span>الاستراحة: غير مدفوعة</span><span>التقييم: مستمر</span></div><div class="action-row"><button id="startAnnot" class="primary-btn">ابدأ الوردية</button></div></div></div>`);$('#startAnnot').addEventListener('click',()=>go('annotationTask'));}
  function annotationTask(){const i=state.flags.annotationIndex;if(i>=ANNOTATION_TASKS.length){go('annotationReview');return;}const task=ANNOTATION_TASKS[i];html(`<div class="annotation-shell"><div class="annotation-head"><strong>مشروع تصنيف البيانات</strong><span>المهمة ${i+1} من ${ANNOTATION_TASKS.length}</span></div><div class="annotation-body">${task.sensitive?'<div class="alert" style="color:#4b3a10;background:#fff6df;border-color:#d7b563"><strong>تنبيه محتوى</strong><span>وصف مقتضب وغير تفصيلي لمادة حساسة.</span></div>':''}<div class="annotation-stats"><span>المهام المكتملة: ${i}</span><span>المقبولة: ${state.flags.annotationCounts.accepted}</span><span>الدقة: ${Math.max(72,96-i)}%</span>${i>=4?'<span>سرعتك أقل من 61% من الفريق</span>':''}</div><div class="annotation-copy">${task.text}</div><div class="annotation-tags">${ANNOTATION_LABELS.map(t=>`<button data-tag="${t}">${t}</button>`).join('')}</div>${i===5?'<div class="action-row"><button id="takeBreak" class="choice-btn break-btn"><strong>خذ استراحة</strong><small>الاستراحة غير مدفوعة.</small></button></div>':''}</div></div>`);bind('[data-tag]','click',e=>{const choice=e.currentTarget.dataset.tag;if(choice===task.best){state.flags.annotationCounts.accepted++;mutateMetrics({quality:1});}else if(choice==='غير واضح'){state.flags.annotationCounts.pending++;mutateMetrics({quality:1,cost:1,pressure:-1});}else{state.flags.annotationCounts.accepted++;mutateMetrics({quality:-2,pressure:1});}if(task.ambiguity&&choice!=='غير واضح')mutateMetrics({burden:2,pressure:1});state.flags.annotationIndex++;saveState();annotationTask();});$('#takeBreak')?.addEventListener('click',()=>{state.flags.tookBreak=true;addDecision('annotation-break','أخذت استراحة غير مدفوعة','انخفض العبء الفوري لكن الدخل المتوقع والسرعة تراجعا.',{pressure:-3,cost:1,burden:-7,quality:2,visibility:3});state.flags.annotationIndex++;saveState();annotationTask();});}
  function annotationReview(){state.flags.annotationCounts.rejected=1;html(`<div class="annotation-shell"><div class="annotation-head"><strong>مراجعة الجودة</strong><span>اكتملت الوردية</span></div><div class="annotation-body"><h1 style="margin-top:0">المراجع اختلف مع أحد تصنيفاتك.</h1><div class="alert" style="color:#4c1820;background:#feecee;border-color:#e8abb3"><strong>المهمة مرفوضة — الدفع عنها: صفر</strong><span>يمكنك الاعتراض، لكن المراجعة قد تستغرق حتى 48 ساعة.</span></div><div class="choice-grid"><button id="appeal" class="choice-btn" style="color:#18212d;background:white"><strong>اعترض</strong><small>يحتاج إلى وقت إضافي غير مدفوع.</small></button><button id="skipAppeal" class="choice-btn" style="color:#18212d;background:white"><strong>لا تعترض</strong><small>استمر وأغلق الوردية.</small></button></div></div></div>`);$('#appeal').addEventListener('click',()=>{addDecision('annotation-appeal','اعترضت على مهمة مرفوضة','استخدمت مسار الاعتراض لكن وقت المراجعة لا يدخل دخل الوردية.',{burden:2,cost:1,visibility:3});go('annotationEnd');});$('#skipAppeal').addEventListener('click',()=>{addDecision('annotation-noappeal','لم تعترض على المهمة المرفوضة','وفرت الوقت لكن قرار المنصة ظل قائمًا بلا مراجعة.',{pressure:1,cost:-1,burden:1,visibility:1});go('annotationEnd');});}
  function annotationEnd(){addLedger(4,'أماني — عاملة بيانات','تصنيف متكرر، حالات غامضة، محتوى حساس، تقييم جودة واعتراض','أمثلة صنفها البشر','المرحلة التالية ترى أمثلة مصنفة، لا تفاصيل الأجر والاستراحة والرفض.');html(`<div><span class="eyebrow">وردية مكتملة</span><h1 class="scene-title">ماذا أنتج عمل أماني؟</h1><div class="stage-output"><strong>${ANNOTATION_TASKS.length} أمثلة مصنفة أو راجعها البشر</strong>يمكن أن تستخدم هذه الأمثلة في تجهيز البيانات أو تقييم النموذج وتحسينه.</div><div class="card"><div class="hud-grid"><div class="hud-item"><span>مقبولة</span><strong>${state.flags.annotationCounts.accepted}</strong></div><div class="hud-item"><span>قيد المراجعة</span><strong>${state.flags.annotationCounts.pending}</strong></div><div class="hud-item"><span>مرفوضة</span><strong>1</strong></div></div><p class="muted">عند انتقال الناتج إلى فريق التطوير، لا تظهر حالة الدفع أو الاستراحة أو الاعتراض بجوار كل مثال.</p></div><div class="action-row"><button id="annotAbstract" class="primary-btn">شاهد كيف يختصر النظام هذا العمل</button></div></div>`);$('#annotAbstract').addEventListener('click',()=>go('abstract5'));}
  function abstract5(){abstraction([['أماني','عاملة بيانات','⌨']],`${ANNOTATION_TASKS.length} أمثلة مصنفة`,'وقت العمل والقراءة والقرارات الغامضة أصبحت في النظام مجموعة من الأمثلة المصنفة.','ch6Intro');}
  return {ch5Intro,annotationIntro,annotationTask,annotationReview,annotationEnd,abstract5};
}
