import { DATA_ITEMS } from '../data/content-tasks.js';
import { supportingRoleStrip } from '../components/supporting-role-strip.js';
import { hasUnresolved } from '../domain/game-rules.js';
import { DATA_ORIGIN_IDS } from '../domain/game-schema.js';

const ORIGIN_COPY={
  writer:['مقالات ومحتوى مكتوب','راجع الترخيص وسياق النشر وحقوق المؤلف.'],photo:['صور فوتوغرافية','قد تجمع حقوق الصورة وحقوق المصور وبيانات أشخاص ظاهرين فيها.'],code:['شفرة برمجية','وجود المستودع علنًا لا يحدد وحده شروط إعادة الاستخدام.'],research:['أبحاث ودراسات','راجع الترخيص وحقوق الناشر والمواد الملحقة.'],forum:['نقاشات منتديات','قد تتضمن أسماء حسابات وسياقًا شخصيًا إلى جانب المحتوى المفيد.'],translate:['ترجمات','للترجمة حقوق وسياق استخدام قد يختلفان عن النص الأصلي.'],docs:['توثيق ومستندات','قد يكون متاحًا للقراءة مع قيود مختلفة على إعادة الاستخدام.'],qa:['أسئلة وأجوبة','قد تحتوي أمثلة عملية ومعلومات شخصية ضمن السياق.'],web:['صفحات ويب','الوصول التقني إلى الصفحة لا يحسم ملاءمة استخدامها.'],comment:['تعليقات المستخدمين','تحتاج مراجعة الخصوصية والسياق وتوقعات المستخدمين.'],manual:['أدلة تقنية','تحقق من المصدر والترخيص والإصدار قبل إدخال المادة.'],news:['أخبار وتقارير','المحتوى المنشور يظل مرتبطًا بحقوق وشروط استخدام ومخاطر دقة.']
};
const ACTIONS={
  keep:['مرّر المادة','استخدمها في المسار التالي بالحالة الحالية.'],
  remove:['استبعد المادة','أخرجها من الدفعة الحالية.'],
  review:['أوقفها للمراجعة','أبقها خارج المسار التالي إلى أن تُراجع؛ يضيف 4 دقائق.'],
  redact:['نقّح البيانات المباشرة','أزل البيانات التي لا يحتاجها الغرض قبل المرور.']
};
const ACTIONS_BY_TYPE={
  duplicate:['remove','keep','review'],
  clean:['keep','review','remove'],
  pii:['review','redact','keep','remove'],
  code:['review','keep','remove'],
  ambiguous:['review','keep','remove']
};
function actionMarkup(item){return (ACTIONS_BY_TYPE[item.type]||['keep','review','remove']).map(choice=>{const [label,detail]=ACTIONS[choice];return`<button data-sort="${choice}" class="choice-btn"><strong>${label}</strong><small>${detail}</small></button>`;}).join('');}
function choiceEffect(item,choice){if(choice===item.recommended){if(choice==='keep')return['مررت مادة مناسبة لهذا الغرض','كانت الملاءمة والحقوق والخصوصية واضحة في سيناريو الدفعة.'];if(choice==='remove')return['استبعدت النسخة المكررة','منعت تكرار المادة من زيادة حجم الدفعة بلا قيمة إضافية.'];if(choice==='redact')return['نقحت بيانات لا يحتاجها الغرض','احتفظت بالجزء المفيد بعد إزالة معلومات مباشرة لا يحتاجها السيناريو.'];return['أوقفت المادة للمراجعة المناسبة','بقيت خارج المسار التالي مع الاحتفاظ بالأدلة المعروفة عنها.'];}if(choice==='keep')return['مررت مادة قبل اكتمال التحقق','سمحت للمادة بالمرور رغم بقاء مشكلة غير محسومة.'];if(choice==='remove')return['استبعدت مادة بدل معالجة المشكلة المحددة','اخترت الحذف حتى عندما كانت المراجعة أو المعالجة ممكنة.'];if(choice==='redact')return['استخدمت التنقيح قبل حسم بقية الأدلة','عالجت البيانات المباشرة، لكن التنقيح لا يحسم وحده حق الاستخدام.'];return['أرسلت مادة للمراجعة الاحتياطية','أبقيت المادة خارج المسار التالي من دون محو الأدلة السابقة.'];}
function checksFor(item,choice){if(choice==='remove')return{rights:'na',privacy:'na',fitness:'na'};const base={...item.checks};if(choice==='redact'&&item.type==='pii')base.privacy='clear';return base;}
function statusCounts(state){const statuses=state.flags.dataStatuses;let clearPassed=0,passedWithIssues=0;statuses.forEach((status,index)=>{if(status!=='ready')return;if(hasUnresolved(state.flags.dataChecks[index]))passedWithIssues++;else clearPassed++;});return{passed:statuses.filter(status=>status==='ready').length,clearPassed,passedWithIssues,pending:statuses.filter(status=>status==='pending').length,excluded:statuses.filter(status=>status==='excluded').length};}
function feedbackMarkup(state,h){return state.flags.dataFeedbackLabel?`<div class="decision-feedback-inline" role="status"><strong>${h(state.flags.dataFeedbackLabel)}</strong><span>${h(state.flags.dataFeedbackDetail)}</span></div>`:'';}
function checksMarkup(check){if(!check)return'';const label=value=>value==='clear'?'محسوم':value==='na'?'غير منطبق':'غير محسوم';return`<div class="hud-grid"><div class="hud-item"><span>الحقوق</span><strong>${label(check.rights)}</strong></div><div class="hud-item"><span>الخصوصية</span><strong>${label(check.privacy)}</strong></div><div class="hud-item"><span>الملاءمة</span><strong>${label(check.fitness)}</strong></div></div>`;}

export function createDataRoutes(ctx){
  const $=ctx.$,state=ctx.state;const {chapterIntro,html,go,bind,saveState,addDecision,addLedger}=ctx;const abstraction=(humans,word,line,next)=>ctx.abstraction(humans,word,line,next);
  function ch4Intro(){chapterIntro(3,'dataOrigins');}
  function dataOrigins(){const cards=DATA_ORIGIN_IDS.map(id=>{const [label,detail]=ORIGIN_COPY[id],revealed=state.flags.dataOrigins.includes(id);return revealed?`<article class="data-bit data-bit--label revealed data-bit--static"><strong>${ctx.h(label)}</strong><small>${ctx.h(detail)}</small></article>`:`<button class="data-bit data-bit--label" data-origin="${id}"><strong>${ctx.h(label)}</strong><small>استكشاف اختياري</small></button>`;}).join('');html(`<div><span class="eyebrow">من المحتوى إلى مواد البيانات</span><h1 class="scene-title">قبل أن تصبح المادة «بيانات»، كانت محتوى له مصدر وسياق.</h1>${supportingRoleStrip(['contentCreators'],'من يقف قبل مرحلة تجهيز البيانات؟')}<p class="scene-subtitle">المهمة الأساسية هي مراجعة الدفعة. يمكنك البدء فورًا أو استكشاف أمثلة المصادر.</p><div class="reality-note"><strong>فرق مهم</strong> حالة المسار وحالة الدليل منفصلتان.</div><div class="action-row"><button id="toClean" class="primary-btn">ابدأ مراجعة الدفعة</button></div><details class="optional-source-details"${state.flags.dataOrigins.length?' open':''}><summary>استكشف أمثلة لمصادر البيانات — اختياري</summary><div class="data-cloud data-cloud--labels">${cards}</div></details></div>`);bind('[data-origin]','click',event=>{const id=event.currentTarget.dataset.origin;if(!state.flags.dataOrigins.includes(id))state.flags.dataOrigins.push(id);saveState();dataOrigins();});$('#toClean')?.addEventListener('click',()=>go('dataClean'));}
  function dataFollowup(){const followup=state.flags.dataFollowup;if(!followup){go('dataClean');return;}const item=DATA_ITEMS[followup.index];html(`<div><span class="eyebrow">نتيجة مراجعة الحقوق</span><h1 class="scene-title">ظهر دليل يسمح بالاستخدام، لكن مشكلة الخصوصية ما زالت قائمة.</h1>${supportingRoleStrip(['rightsReviewer'],'من راجع دليل الاستخدام؟')}<div class="card flat"><p><strong>المادة:</strong> ${ctx.h(item.title)}</p><p><strong>ما حُسم:</strong> حق الاستخدام في هذا المثال فقط.</p><p><strong>ما لم يُحسم:</strong> بيانات الاتصال لا يحتاجها غرض الدفعة.</p></div><div class="choice-grid"><button id="followupRedact" class="choice-btn"><strong>نقّح بيانات الاتصال</strong></button><button id="followupKeep" class="choice-btn"><strong>احتفظ بها كما هي</strong><small>مشكلة الخصوصية تظل مسجلة.</small></button></div></div>`);$('#followupRedact').addEventListener('click',()=>{state.flags.dataSort.redact++;state.flags.dataStatuses[followup.index]='ready';state.flags.dataChecks[followup.index]={rights:'clear',privacy:'clear',fitness:'clear'};state.flags.dataFeedbackLabel='مرّت المادة بعد حسم المشكلتين';state.flags.dataFeedbackDetail='ظهر دليل يسمح بالاستخدام، ثم أزال التنقيح بيانات الاتصال غير اللازمة.';state.flags.dataFollowup=null;state.flags.dataIndex++;addDecision('data-pii-redact-after-review','نقحت البيانات بعد مراجعة دليل الحقوق','راجع فريق الحقوق دليل الاستخدام أولًا، ثم أزلت بيانات الاتصال غير اللازمة.');saveState();go('dataClean');});$('#followupKeep').addEventListener('click',()=>{state.flags.dataSort.keep++;state.flags.dataStatuses[followup.index]='ready';state.flags.dataChecks[followup.index]={rights:'clear',privacy:'unresolved',fitness:'clear'};state.flags.dataFeedbackLabel='مرّت المادة، لكن مشكلة الخصوصية بقيت';state.flags.dataFeedbackDetail='حق الاستخدام حُسم، لكن بيانات الاتصال غير اللازمة بقيت.';state.flags.dataFollowup=null;state.flags.dataIndex++;addDecision('data-pii-keep-after-review','مررت مادة مع مشكلة خصوصية غير محسومة','ظهر دليل يسمح بالاستخدام، لكن بيانات الاتصال بقيت رغم أن الغرض لا يحتاجها.');saveState();go('dataClean');});}
  function dataClean(){if(state.flags.dataFollowup){go('dataFollowup');return;}const index=state.flags.dataIndex;if(index>=DATA_ITEMS.length){go('dataCleanSummary');return;}const item=DATA_ITEMS[index],counts=statusCounts(state),feedback=feedbackMarkup(state,ctx.h);html(`<div><span class="eyebrow">دفعة بيانات رقم 18</span><h1 class="scene-title">أنت الآن نور، متخصصة تجهيز بيانات.</h1>${feedback}<div class="reality-note"><strong>المهمة الحالية</strong> اختر الإجراء الذي يناسب المشكلة المعروضة في هذه المادة. لا تعرض اللعبة إجراءً لا معنى له لمجرد توحيد الأزرار.</div><div class="hud-grid"><div class="hud-item"><span>العنصر</span><strong>${index+1}/${DATA_ITEMS.length}</strong></div><div class="hud-item"><span>وقت المراجعة الإضافي</span><strong>${state.flags.dataReviewMinutes} دقيقة</strong></div><div class="hud-item"><span>مرّت / معلقة</span><strong>${counts.passed} / ${counts.pending}</strong></div></div><div class="sort-layout"><div class="data-item card"><span class="kicker">${ctx.h(item.title)}</span><div class="data-preview">${ctx.h(item.body)}</div><div class="card flat"><p><strong>المصدر:</strong> ${ctx.h(item.source)}</p><p><strong>حالة الحقوق:</strong> ${ctx.h(item.rights)}</p><p><strong>الخصوصية:</strong> ${ctx.h(item.privacy)}</p></div></div><div class="sort-actions">${actionMarkup(item)}</div></div></div>`);bind('[data-sort]','click',event=>{const choice=event.currentTarget.dataset.sort,[label,effectText]=choiceEffect(item,choice);state.flags.dataSort[choice]++;if(choice==='review')state.flags.dataReviewMinutes+=4;addDecision(`data-${item.type}-${choice}`,label,effectText);if(item.followup&&choice===item.recommended){state.flags.dataFollowup={index};state.flags.dataFeedbackLabel='';state.flags.dataFeedbackDetail='';saveState();go('dataFollowup');return;}const status=choice==='review'?'pending':choice==='remove'?'excluded':'ready',checks=checksFor(item,choice);state.flags.dataStatuses[index]=status;state.flags.dataChecks[index]=checks;state.flags.dataFeedbackLabel=label;state.flags.dataFeedbackDetail=`${effectText}${status==='ready'&&hasUnresolved(checks)?' المادة مرّت، لكن توجد مسألة واحدة على الأقل ما زالت غير محسومة.':''}`;state.flags.dataIndex++;saveState();dataClean();});}
  function dataCleanSummary(){const counts=statusCounts(state),unresolvedNote=counts.passedWithIssues?`${counts.passedWithIssues} من المواد التي مرّت تحمل مسائل غير محسومة؛ مرورها لا يمحو هذه المسائل.`:'كل المواد التي مرّت في هذا المسار حُسمت مسائلها المعروضة.';addLedger(3,'منتجو المحتوى + نور + مراجعة الحقوق','إنتاج مواد أصلية ثم جمع وفرز وتنقيح ومراجعة الحقوق والخصوصية والملاءمة',`${counts.passed} مواد مرّت + ${counts.pending} معلقة`,unresolvedNote);html(`<div><span class="eyebrow">نتيجة تجهيز البيانات</span><h1 class="scene-title">انتهت مراجعة الدفعة، لكن الحالات ليست متطابقة.</h1><div class="hud-grid"><div class="hud-item"><span>مرّت بلا حاجب</span><strong>${counts.clearPassed}</strong></div><div class="hud-item"><span>مرّت بمسألة مفتوحة</span><strong>${counts.passedWithIssues}</strong></div><div class="hud-item"><span>معلقة</span><strong>${counts.pending}</strong></div><div class="hud-item"><span>مستبعدة</span><strong>${counts.excluded}</strong></div></div><div class="evidence-results">${state.flags.dataStatuses.map((status,index)=>`<article class="card flat"><strong>${ctx.h(DATA_ITEMS[index]?.title||`المادة ${index+1}`)}</strong><p>حالة المسار: ${status==='ready'?'مرّت':status==='pending'?'معلقة':'مستبعدة'}</p>${checksMarkup(state.flags.dataChecks[index])}</article>`).join('')}</div><div class="action-row"><button id="dataDone" class="primary-btn">انتقل إلى التصنيف البشري</button></div></div>`);$('#dataDone').addEventListener('click',()=>go('abstract4'));}
  function abstract4(){const counts=statusCounts(state);abstraction([['نور','تجهيز بيانات','◫'],['منتجو المحتوى','','◇'],['مراجع الحقوق','','⌕']],`${counts.passed} مواد مرّت + ${counts.pending} معلقة`,'حالة المسار لا تمحو أسئلة المصدر والحقوق والخصوصية والملاءمة.','ch5Intro');}
  return{ch4Intro,dataOrigins,dataClean,dataFollowup,dataCleanSummary,abstract4};
}