import { SUPPORT_TASKS } from '../data/game-data.js';
export function createDeploymentRoutes(ctx){
  const $=ctx.$, state=ctx.state;
  const {setChapter,chapterIntro,html,go,bind,tone,saveState,mutateMetrics,addDecision,addLedger}=ctx;
  const abstraction=(humans,word,line,next)=>ctx.abstraction(humans,word,line,next);
  function ch8Intro(){chapterIntro(7,'','','deployLoad');}
  function deployLoad(){setChapter(7);html(`<div><span class="eyebrow">هانا — مهندسة تشغيل الخدمة</span><h1 class="scene-title">أصبحت الخدمة متاحة للمستخدمين.</h1><div class="reality-note"><strong>ما معنى تشغيل الخدمة؟</strong> بعد تدريب النموذج لا يظل يعمل وحده. يجب توزيع طلبات المستخدمين بين الخوادم، ومراقبة السرعة والأعطال، والاستجابة عندما يتوقف جزء من النظام.</div><p class="scene-subtitle">وزّع الحمل بين ثلاثة مراكز بيانات. مجموع القيم لا يحتاج أن يكون مثاليًا؛ الهدف أن ترى القيود المختلفة.</p><div class="load-grid">${['أ','ب','ج'].map((x,i)=>`<div class="load-card"><span>مركز البيانات ${x}</span><strong id="load${i}">${[34,33,33][i]}%</strong><input id="range${i}" type="range" min="0" max="100" value="${[34,33,33][i]}" /></div>`).join('')}</div><div id="loadFeedback" class="alert"><strong>الحالة</strong><span>حرّك الأحمال ثم شغّل الاختبار.</span></div><div class="action-row"><button id="testLoad" class="primary-btn">اختبر التوزيع</button></div></div>`);[0,1,2].forEach(i=>$('#range'+i).addEventListener('input',e=>$('#load'+i).textContent=e.target.value+'%'));$('#testLoad').addEventListener('click',()=>{const vals=[0,1,2].map(i=>Number($('#range'+i).value)),total=vals.reduce((a,b)=>a+b,0),max=Math.max(...vals);if(total<90||total>110){$('#loadFeedback').innerHTML='<strong>التوزيع غير متوازن</strong><span>حاول إبقاء مجموع الأحمال قريبًا من 100%.</span>';tone(170,.08,'square');return;}if(max>60)mutateMetrics({burden:3,quality:-2,pressure:2});else mutateMetrics({quality:2});go('deployIncident');});}
  function deployIncident(){const tabs=[['network','الشبكة','الشبكة مستقرة، ولا توجد زيادة واضحة في فقد البيانات.'],['compute','الخوادم','السعة متاحة، لكن بعض العمليات تُعاد تشغيلها.'],['model','خدمة النموذج','استهلاك الذاكرة يرتفع تدريجيًا في الإصدار الجديد.']];html(`<div><span class="eyebrow">عطل في الخدمة</span><h1 class="scene-title">ارتفعت نسبة الأخطاء إلى 12%</h1><div class="alert dangerish"><strong>12,417 مستخدمًا متأثرًا — رقم افتراضي داخل اللعبة</strong><span>افتح الأقسام الثلاثة لتحديد مكان المشكلة.</span></div><div class="incident-tabs">${tabs.map(([id,label])=>`<button data-tab="${id}" class="${state.flags.deployTabs.includes(id)?'active':''}">${label}</button>`).join('')}</div><div id="tabReadout" class="card flat">افتح الشبكة والخوادم وخدمة النموذج.</div>${state.flags.deployTabs.length===3?'<div class="choice-grid"><button id="restartInst" class="choice-btn"><strong>أعد تشغيل الوحدات المتأثرة</strong><small>عودة أسرع مع احتمال تكرار المشكلة.</small></button><button id="rollback" class="choice-btn"><strong>ارجع إلى الإصدار السابق</strong><small>وقت أطول لكن العودة إلى إصدار أكثر استقرارًا.</small></button></div>':''}</div>`);bind('[data-tab]','click',e=>{const id=e.currentTarget.dataset.tab,t=tabs.find(x=>x[0]===id);$('#tabReadout').textContent=t[2];if(!state.flags.deployTabs.includes(id)){state.flags.deployTabs.push(id);saveState();deployIncident();}});$('#restartInst')?.addEventListener('click',()=>{addDecision('deploy-restart','أعدت تشغيل الوحدات المتأثرة','عادت الخدمة أسرع مع احتمال بقاء سبب العطل.',{pressure:5,cost:-3,burden:5,quality:-3,visibility:1});go('onCall');});$('#rollback')?.addEventListener('click',()=>{addDecision('deploy-rollback','عدت إلى الإصدار السابق','تحملت وقت استعادة أطول مقابل استقرار أعلى.',{pressure:-3,cost:4,burden:1,quality:5,visibility:2});go('onCall');});}
  function onCall(){html(`<div><span class="eyebrow">بعد استعادة الخدمة</span><h1 class="scene-title">الخدمة تعمل. الوردية لم تنتهِ.</h1><div class="role-card card flat"><div class="avatar">◉</div><div><h3>هانا</h3><p>مهندسة تشغيل ضمن مناوبة طوارئ؛ يمكن استدعاؤها عند ظهور عطل خارج وقت العمل المعتاد.</p></div></div><div class="card"><p>تجلس هانا للاستراحة. يهتز الهاتف.</p><div class="alert dangerish"><strong>تنبيه جديد من نظام المراقبة</strong><span>هناك مشكلة أخرى تحتاج إلى مراجعة.</span></div></div><div class="action-row"><button id="toSupport" class="primary-btn">استمر إلى دعم المستخدمين</button></div></div>`);$('#toSupport').addEventListener('click',()=>go('supportTask'));}
  function supportTask(){const i=state.flags.supportIndex;if(i>=SUPPORT_TASKS.length){go('deployEnd');return;}const t=SUPPORT_TASKS[i];html(`<div><span class="eyebrow">سامر — دعم المستخدمين</span><h1 class="scene-title">رسالة مستخدم ${i+1}/${SUPPORT_TASKS.length}</h1><p class="scene-subtitle">جزء من تشغيل المنتج ليس تقنيًا فقط؛ هناك أيضًا عمال يتعاملون مع الحسابات والدفع والأخطاء التي يواجهها المستخدمون.</p><div class="card"><div class="message user">${t.q}</div><div class="choice-grid"><button id="supportGood" class="choice-btn"><strong>${t.a}</strong></button><button id="supportGeneric" class="choice-btn"><strong>أرسل ردًا عامًا وأغلق الحالة</strong><small>أسرع، لكنه قد لا يحل المشكلة.</small></button></div></div></div>`);$('#supportGood').addEventListener('click',()=>{mutateMetrics({quality:2,visibility:1});state.flags.supportIndex++;saveState();supportTask();});$('#supportGeneric').addEventListener('click',()=>{mutateMetrics({pressure:2,quality:-2});state.flags.supportIndex++;saveState();supportTask();});}
  function deployEnd(){addLedger(7,'هانا وسامر وفرق العمليات','مراقبة الخدمة، الاستجابة للأعطال، المناوبات والدعم','الخدمة متاحة للمستخدمين','تظهر نتيجة هذا العمل للمستخدم كخدمة سريعة ومتاحة، لا كورديات تشغيل ودعم.');html(`<div><span class="eyebrow">نهاية مرحلة التشغيل</span><h1 class="scene-title">ماذا أنتجت هذه المرحلة؟</h1><div class="stage-output"><strong>خدمة متاحة يستطيع المستخدم إرسال طلبه إليها</strong>خلف كلمة «متاحة» توجد مراقبة وأعطال ومناوبات ودعم وصيانة.</div><div class="card"><div class="hud-grid"><div class="hud-item"><span>توافر الخدمة</span><strong>99.9%</strong></div><div class="hud-item"><span>الحالة</span><strong>متاحة</strong></div><div class="hud-item"><span>العمل البشري في الواجهة</span><strong>غير ظاهر</strong></div></div></div><div class="action-row"><button id="uptimeAbstract" class="primary-btn">شاهد كيف يختصر المنتج هذا العمل</button></div></div>`);$('#uptimeAbstract').addEventListener('click',()=>go('abstract8'));}
  function abstract8(){abstraction([['هانا','التشغيل','◉'],['سامر','الدعم','☏'],['فرق الشبكات','','≋']],'الخدمة متاحة','المناوبات وإصلاح الأعطال ودعم المستخدمين أصبحت للمستخدم حالة واحدة: الخدمة تعمل.','ch9Intro');}
  return {ch8Intro,deployLoad,deployIncident,onCall,supportTask,deployEnd,abstract8};
}
