export function createTrainingRoutes(ctx){
  const $=ctx.$, state=ctx.state;
  const {setChapter,chapterIntro,html,go,saveState,addDecision,addLedger}=ctx;
  function ch6Intro(){chapterIntro(5,'','','trainingSetup');}
  function trainingSetup(){setChapter(5);html(`<div><span class="eyebrow">مختبر تدريب افتراضي</span><h1 class="scene-title">أنت الآن ديفيد، مهندس تعلم آلي.</h1><div class="reality-note"><strong>ما المقصود بتدريب النموذج؟</strong> النموذج برنامج رياضي يحتوي على عدد كبير من القيم الداخلية. أثناء التدريب تُعرض عليه أمثلة كثيرة، وتُعدَّل هذه القيم تدريجيًا حتى يتحسن في توقع النص وإنتاجه. هذه العملية تحتاج إلى البيانات والخوادم معًا.</div><div class="training-board"><div class="config-panel"><div class="form-row"><label>مجموعة البيانات</label><select id="datasetSel"><option>الإصدار 18 — جاهز</option></select></div><div class="form-row"><label>الخوادم المخصصة للتدريب</label><select id="computeSel"><option>12 مجموعة خوادم</option><option>8 مجموعات خوادم</option></select></div><div class="form-row"><label>النسخة التي يبدأ منها التدريب</label><select id="checkpointSel"><option>نسخة الأساس 04</option><option>نسخة الأساس 03</option></select><small class="term-note">هذه نسخة محفوظة من حالة النموذج يمكن بدء التدريب منها أو العودة إليها.</small></div><button id="trainStart" class="primary-btn" style="width:100%">ابدأ التدريب</button></div><div class="chart-panel"><span class="kicker">معاينة عملية التدريب</span><div class="training-graph"><div class="training-line"><svg viewBox="0 0 400 200" preserveAspectRatio="none"><polyline fill="none" stroke="rgba(104,225,193,.9)" stroke-width="4" points="0,30 40,55 80,70 120,92 160,110 200,126 240,138 280,149 320,158 360,166 400,172"/></svg></div></div><div class="training-log" dir="rtl" style="text-align:right;font-family:inherit">مجموعة البيانات: جاهزة<br>الخوادم: متاحة<br>نسخة البداية: جاهزة</div></div></div></div>`);$('#trainStart').addEventListener('click',()=>{state.flags.trainingConfigured=true;saveState();go('trainingRun');});}
  function trainingRun(){html(`<div><span class="eyebrow">جولة التدريب</span><h1 class="scene-title">بدأ التدريب على الخوادم.</h1><div class="chart-panel"><div class="hud-grid"><div class="hud-item"><span>التقدم</span><strong>35%</strong></div><div class="hud-item"><span>مؤشر الخطأ</span><strong>ينخفض ↓</strong></div><div class="hud-item"><span>الخوادم المتاحة</span><strong>11/12</strong></div></div><div class="training-graph"><div class="training-line"><svg viewBox="0 0 400 200" preserveAspectRatio="none"><polyline fill="none" stroke="rgba(124,164,255,.95)" stroke-width="4" points="0,25 50,60 100,83 150,112 200,125 245,138 270,100 295,145 350,157 400,166"/></svg></div></div><div class="alert dangerish"><strong>إحدى وحدات الحوسبة غير متاحة</strong><span>يمكن إيقاف الجولة وتشخيص المشكلة أو الاستمرار بقدرة أقل.</span></div></div><div class="choice-grid"><button id="trainPause" class="choice-btn"><strong>أوقف التدريب وافحص العطل</strong><small>تأخير أعلى مع تشخيص أوضح.</small></button><button id="trainContinue" class="choice-btn"><strong>استمر بقدرة أقل</strong><small>استمرار أبطأ مع ضغط أعلى على الموارد المتبقية.</small></button></div></div>`);$('#trainPause').addEventListener('click',()=>{addDecision('train-pause','أوقفت جولة التدريب لتشخيص عطل','تحملت تكلفة تأخير بدل الاستمرار بحالة غير مستقرة.',{pressure:-3,cost:5,burden:-2,quality:5,visibility:2});go('trainingEval');});$('#trainContinue').addEventListener('click',()=>{addDecision('train-continue','واصلت التدريب بقدرة أقل','حافظت على الجولة لكنها أصبحت أبطأ وارتفع الضغط على البنية.',{pressure:4,cost:-1,burden:3,quality:-2,visibility:1});go('trainingEval');});}
  function trainingEval(){addLedger(5,'ديفيد وفرق التدريب','إعداد وتشغيل ومراقبة جولات التدريب وحل أعطال الخوادم','نسخة مدرَّبة من النموذج','التدريب لا يلغي الحاجة إلى تقييم بشري لاحق لجودة وسلوك النموذج.');html(`<div><span class="eyebrow">اختبار أولي</span><h1 class="scene-title">انتهى التدريب، لكن النموذج ليس جاهزًا للإطلاق.</h1><div class="stage-output"><strong>ماذا أنتجت هذه المرحلة؟</strong>نسخة من النموذج تستطيع إنتاج إجابات، لكنها ما زالت تحتاج إلى تقييم الدقة واللغة والسلامة.</div><div class="card"><div class="message ai">س: ما عاصمة فرنسا؟<br><strong>باريس.</strong></div><div class="message ai">س: اكتب رسالة رسمية.<br><strong>إجابة مقبولة.</strong></div><div class="message ai">س: رد بالمصرية على طلب بسيط.<br><strong>«أتشرف بإحاطة سيادتكم علمًا...»</strong></div><div class="alert"><strong>المشكلة</strong> بعض الاختبارات ناجحة، وبعضها يكشف ضعفًا في اللغة والسياق والسلوك.</div></div><div class="action-row"><button id="sendHuman" class="primary-btn">أرسل النموذج للمراجعة البشرية</button></div></div>`);$('#sendHuman').addEventListener('click',()=>go('ch7Intro'));}
  return {ch6Intro,trainingSetup,trainingRun,trainingEval};
}
