import { chromium, firefox, webkit } from 'playwright';
import AxeBuilder from '@axe-core/playwright';
import { DEFAULT_STATE, clone, STATE_SCHEMA_VERSION } from '../js/core/state.js';
import { STORAGE_KEY, SETTINGS_KEY, DEFAULT_SETTINGS } from '../js/core/storage.js';
import { DEMO_PROMPT } from '../js/data/story.js';
import { stateWith, BASE_URL } from './helpers/browser-fixtures.mjs';

const TEST_SETTINGS={...DEFAULT_SETTINGS,reduceMotion:true};
async function load(page,patch=null){await page.goto(BASE_URL,{waitUntil:'networkidle'});const state=patch?stateWith(patch):null;await page.evaluate(({state,settings})=>{localStorage.clear();localStorage.setItem('behindTheAnswerSettings',JSON.stringify(settings));if(state)localStorage.setItem('behindTheAnswerGame',JSON.stringify(state));},{state,settings:TEST_SETTINGS});await page.reload({waitUntil:'networkidle'});}
const click=async(page,selector)=>{await page.locator(selector).waitFor({state:'visible'});await page.locator(selector).click();};
const saved=page=>page.evaluate(key=>JSON.parse(localStorage.getItem(key)),STORAGE_KEY);
const chooseData=(page,choice)=>click(page,`[data-sort="${choice}"]`);
const chooseAnnotation=(page,label)=>click(page,`[data-tag="${label}"]`);
async function setLoad(page,values){await page.evaluate(next=>next.forEach((value,index)=>{const input=document.querySelector(`#range${index}`);input.value=String(value);input.dispatchEvent(new Event('input',{bubbles:true}));}),values);}
async function completeCheckpoint(page){for(const [id,value] of Object.entries({apology:'b',legal:'a',friendly:'b'}))await page.selectOption(`[data-checkpoint-sample="${id}"]`,value);await click(page,'#checkCheckpoint');await click(page,'#toSafety');}
async function completeRelease(page){if(await page.locator('#toReleaseGates').count())await click(page,'#toReleaseGates');await click(page,'[data-gate-pass="regression"]');await click(page,'[data-gate-investigate="capacity"]');await click(page,'[data-gate-remediate="capacity"]');await click(page,'[data-gate-remeasure="capacity"]');await click(page,'[data-gate-pass="capacity"]');await click(page,'[data-gate-pass="risk"]');await click(page,'[data-gate-pass="rollback"]');await click(page,'#toLaunchDecision');for(const id of ['checkpoint','stability'])if(await page.locator(`[data-extra-check="${id}"]`).count())await click(page,`[data-extra-check="${id}"]`);if(await page.locator('#delayLaunch').count())await click(page,'#delayLaunch');else await click(page,'#launchReady');}
async function completeFailover(page){for(const index of [0,1,2])await click(page,`[data-failover-check="${index}"]`);await page.getByText(/حالات يمكن امتصاصها/).waitFor({state:'visible'});await click(page,'#finishFailover');}
async function completeTransfer(page){for(const [id,value] of Object.entries({weights:'build',retrieval:'request',inference:'request',monitoring:'continuous',maintenance:'continuous'}))await page.selectOption(`[data-transfer-item="${id}"]`,value);await click(page,'#transferSubmit');}

async function runJourney(viewport,label){
 const browser=await chromium.launch(),page=await browser.newPage({viewport}),errors=[];page.on('pageerror',e=>errors.push(e.message));await load(page);
 await click(page,'#introSend');await click(page,'#descend');await click(page,'#chapterNext');await click(page,'#startMine');await click(page,'[data-sector="b"]');await click(page,'[data-sector="b"]');await click(page,'#mineStop');await click(page,'#finishMine');for(let i=0;i<4;i++)await click(page,'[data-sector="b"]');await click(page,'#mineAbstract');await click(page,'#abstractNext');
 await click(page,'#chapterNext');await click(page,'#enterFab');await click(page,'#observeFab');await click(page,'#fabContinue');await click(page,'#startFactoryMaintenance');await click(page,'#diagnoseFactory');await click(page,'#repairFactory');await click(page,'#verifyFactoryRepair');await click(page,'#toFactoryAbstract');await click(page,'#abstractNext');
 await click(page,'#chapterNext');for(const step of ['rack','network','power','register'])await click(page,`[data-server-step="${step}"]`);await click(page,'#bootServer');await click(page,'#dcMove');await click(page,'#repairCooling');await click(page,'#verifyCooling');await click(page,'#dcAfterCooling');await click(page,'#dcReady');await click(page,'#abstractNext');
 await click(page,'#chapterNext');await click(page,'#toClean');await chooseData(page,'remove');await chooseData(page,'keep');await chooseData(page,'review');await click(page,'#followupRedact');await chooseData(page,'review');await chooseData(page,'review');await click(page,'#dataDone');await click(page,'#abstractNext');
 await click(page,'#chapterNext');await click(page,'#startAnnot');for(const choice of ['آمن','عنف','مضايقة أو إساءة'])await chooseAnnotation(page,choice);await click(page,'#takeBreak');for(const choice of ['غير واضح','خطاب كراهية','غير واضح'])await chooseAnnotation(page,choice);if(await page.locator('#appeal').count())await click(page,'#appeal');await click(page,'#annotAbstract');await click(page,'#abstractNext');
 await click(page,'#chapterNext');await page.selectOption('#checkpointSel','recent');await click(page,'#trainStart');let state=await saved(page);if(STATE_SCHEMA_VERSION!==7||Object.hasOwn(state.flags,'trainingCompute')||Object.hasOwn(state.flags,'tookBreak')||Object.hasOwn(state.flags,'dcCoolingRestored'))throw new Error(`${label}: obsolete schema state survived.`);await click(page,'#trainContinue');await click(page,'#sendHuman');await click(page,'#abstractNext');
 await click(page,'#chapterNext');for(const choice of ['a','b','bad']){if(choice==='b')await page.getByText(DEMO_PROMPT,{exact:true}).waitFor({state:'visible'});await click(page,`[data-eval="${choice}"]`);await click(page,'#nextEval');}if(await page.locator('#calibrationChoice').count())await page.selectOption('#calibrationChoice','a');await click(page,'#confirmCalibration');await completeCheckpoint(page);await click(page,'[data-safety="details"]');await click(page,'#remediateSafety');await click(page,'#confirmSafetyRetest');await completeRelease(page);await click(page,'#finishEval');await click(page,'#abstractNext');
 await click(page,'#chapterNext');await setLoad(page,[45,30,25]);await click(page,'#testLoad');await completeFailover(page);await click(page,'#openTraffic');for(const tab of ['network','compute','model'])await click(page,`[data-tab="${tab}"]`);await click(page,'#rollback');await click(page,'#verifyRecovery');await click(page,'#toSupport');await click(page,'#supportInvestigate');await click(page,'#supportFast');await click(page,'#uptimeAbstract');await click(page,'#abstractNext');
 await click(page,'#backPrompt');await click(page,'#transferFromAnswer');await completeTransfer(page);await click(page,'#transferContinue');state=await saved(page);if(!state.flags.deployTrafficOpen||state.flags.deployRecoveryVerifiedFor!=='rollback')throw new Error(`${label}: explicit deployment state missing.`);const displayed=await page.locator('.full-evidence-details .decision-row').count();if(displayed!==state.decisions.length)throw new Error(`${label}: result record mismatch ${displayed}/${state.decisions.length}.`);if(errors.length)throw new Error(`${label}: page errors ${errors.join(' | ')}`);await browser.close();console.log(`Complete journey passed: ${label}`);
}

async function causalChecks(){
 const browser=await chromium.launch(),page=await browser.newPage({viewport:{width:1280,height:900}});
 await load(page,{scene:'factoryIncident'});await click(page,'#fabStop');let s=await saved(page);if(s.flags.factoryProductionComplete)throw new Error('Factory stop completed batch automatically.');await click(page,'#diagnoseFactory');await click(page,'#repairFactory');s=await saved(page);if(s.flags.factoryRemediationStage!=='repaired'||!s.flags.factoryMaintenanceDebt)throw new Error('Factory repair was treated as verification.');await click(page,'#verifyFactoryRepair');if(await page.locator('#toFactoryAbstract').count())throw new Error('Stopped factory batch completed before resume.');await click(page,'#resumeFactory');await page.locator('#toFactoryAbstract').waitFor({state:'visible'});
 await load(page,{scene:'dcCooling',flags:{serverSteps:['rack','power','network','register']}});await click(page,'#dcStop');await click(page,'#repairCooling');s=await saved(page);if(s.flags.dcCoolingStage!=='repaired')throw new Error('Cooling repair auto-verified.');await click(page,'#verifyCooling');s=await saved(page);if(s.flags.dcCoolingStage!=='verified')throw new Error('Cooling verification missing.');
 await load(page,{scene:'trainingRun',flags:{dataIndex:1,dataStatuses:['ready'],dataChecks:[{rights:'clear',privacy:'clear',fitness:'clear'}],dataSort:{keep:1,remove:0,redact:0,review:0},dataTrainingUsed:[0],dataCurrentTrainingUsed:[0],candidateRevision:1}});await click(page,'#trainPause');await click(page,'#repairTrainingCompute');s=await saved(page);if(s.flags.trainingIncidentChoice!==null||s.flags.trainingRecoveryStage!=='repaired')throw new Error('Training repair auto-verified.');await click(page,'#verifyTrainingCompute');await click(page,'#resumeTraining');
 await load(page,{scene:'releaseGateReview',flags:{dataIndex:1,dataStatuses:['ready'],dataChecks:[{rights:'clear',privacy:'clear',fitness:'clear'}],dataSort:{keep:1,remove:0,redact:0,review:0},dataTrainingUsed:[0],dataCurrentTrainingUsed:[0],candidateRevision:1,trainingIncidentChoice:'pause',trainingRecoveryStage:'verified',evalIndex:3,evalCorrectCount:3,evaluatorCalibrationComplete:true,checkpointEvalComplete:true,safetyChoice:'details',safetyRemediated:true,safetyRetested:true}});await click(page,'[data-gate-investigate="capacity"]');await click(page,'[data-gate-remediate="capacity"]');s=await saved(page);if(s.flags.releaseCapacityStage!=='remediated'||s.flags.releaseGates.includes('capacity'))throw new Error('Capacity remediation auto-measured.');await click(page,'[data-gate-remeasure="capacity"]');
 await load(page,{scene:'deployLoad',flags:{dataIndex:1,dataStatuses:['ready'],dataChecks:[{rights:'clear',privacy:'clear',fitness:'clear'}],dataSort:{keep:1,remove:0,redact:0,review:0},dataTrainingUsed:[0],dataCurrentTrainingUsed:[0],candidateRevision:1,trainingIncidentChoice:'pause',trainingRecoveryStage:'verified',evalIndex:3,evalCorrectCount:3,evaluatorCalibrationComplete:true,checkpointEvalComplete:true,safetyChoice:'details',safetyRemediated:true,safetyRetested:true,releaseGates:['regression','capacity','risk','rollback'],releaseCapacityStage:'remeasured',launchChoice:'ready'}});if(await page.getByText(/السقف الممكن.*1\/3/).count())throw new Error('Failover ceiling leaked before tests.');await setLoad(page,[45,30,25]);await click(page,'#testLoad');await completeFailover(page);s=await saved(page);if(s.scene!=='deployGoLive'||s.flags.deployTrafficOpen)throw new Error('Failover opened traffic automatically.');await click(page,'#openTraffic');s=await saved(page);if(!s.flags.deployTrafficOpen)throw new Error('Explicit traffic-open action not persisted.');
 await browser.close();console.log('Causal checks passed.');
}

async function accessibilityCheck(){const browser=await chromium.launch(),page=await browser.newPage({viewport:{width:1280,height:900}});await load(page);const results=await new AxeBuilder({page}).analyze();if(results.violations.length)throw new Error(`Accessibility violations: ${results.violations.map(v=>v.id).join(', ')}`);await browser.close();console.log('Accessibility check passed.');}
async function engineSmoke(engine,name){const browser=await engine.launch(),page=await browser.newPage();await load(page);await click(page,'#introSend');await page.getByRole('heading',{name:'الإجابة هي آخر نقطة مرئية في سلسلة أطول.',exact:true}).waitFor({state:'visible'});await browser.close();console.log(`${name} smoke passed.`);}

await runJourney({width:1280,height:900},'desktop');
await runJourney({width:390,height:844},'mobile');
await causalChecks();
await accessibilityCheck();
await engineSmoke(firefox,'Firefox');
await engineSmoke(webkit,'WebKit');
console.log('Browser suite passed.');
