import { chromium, firefox, webkit } from 'playwright';
import AxeBuilder from '@axe-core/playwright';
import { DEFAULT_STATE, clone } from '../js/core/state.js';
import { STORAGE_KEY, SETTINGS_KEY, DEFAULT_SETTINGS } from '../js/core/storage.js';
import { DEMO_PROMPT } from '../js/data/story.js';

const BASE_URL='http://127.0.0.1:4173';
const TEST_SETTINGS={...DEFAULT_SETTINGS,reduceMotion:true};
function currentState(patch={}){
  const state=clone(DEFAULT_STATE);
  const merge=(target,source)=>Object.entries(source).forEach(([key,value])=>{if(value&&typeof value==='object'&&!Array.isArray(value)){if(!target[key]||typeof target[key]!=='object'||Array.isArray(target[key]))target[key]={};merge(target[key],value);}else target[key]=value;});
  merge(state,patch);
  const revision=state.flags.candidateRevision;
  if(revision>0){for(const decision of [{id:`training-compute-8-r${revision}`,label:'إعداد حوسبة',effectText:'fixture'},{id:`training-checkpoint-${state.flags.trainingCheckpoint}-r${revision}`,label:'إعداد نقطة حفظ',effectText:'fixture'}])if(!state.decisions.some(item=>item.id===decision.id))state.decisions.push(decision);}
  if(state.flags.deployLoad&&state.flags.deployFailoverChecks.length===3){const id=`deploy-resilience-risk-${state.flags.deployLoad.join('-')}`;if(!state.decisions.some(decision=>decision.id===id))state.decisions.push({id,label:'قبول فجوة المرونة',effectText:'fixture'});}
  return state;
}
async function load(page,patch=null,settings=TEST_SETTINGS){await page.goto(BASE_URL,{waitUntil:'networkidle'});await page.evaluate(({storageKey,settingsKey,state,settingsValue})=>{localStorage.clear();if(settingsValue)localStorage.setItem(settingsKey,JSON.stringify(settingsValue));if(state)localStorage.setItem(storageKey,JSON.stringify(state));},{storageKey:STORAGE_KEY,settingsKey:SETTINGS_KEY,state:patch?currentState(patch):null,settingsValue:settings});await page.reload({waitUntil:'networkidle'});}
async function saved(page){return page.evaluate(key=>JSON.parse(localStorage.getItem(key)),STORAGE_KEY);}
async function click(page,selector){const target=page.locator(selector);await target.waitFor({state:'visible'});await target.click();}
async function chooseData(page,choice){await click(page,`[data-sort="${choice}"]`);}
async function chooseAnnotation(page,label){await click(page,`[data-tag="${label}"]`);}
async function setLoad(page,values){await page.evaluate(next=>next.forEach((value,index)=>{const input=document.querySelector(`#range${index}`);input.value=String(value);input.dispatchEvent(new Event('input',{bubbles:true}));}),values);}
async function completeCheckpoint(page){for(const [id,value] of Object.entries({apology:'b',legal:'a',friendly:'b'}))await page.selectOption(`[data-checkpoint-sample="${id}"]`,value);await click(page,'#checkCheckpoint');await click(page,'#toSafety');}
async function completeRelease(page,{delay=true}={}){
  if(await page.locator('#toReleaseGates').count())await click(page,'#toReleaseGates');
  await click(page,'[data-gate-pass="regression"]');await click(page,'[data-gate-investigate="capacity"]');await click(page,'[data-gate-remediate="capacity"]');await click(page,'[data-gate-pass="capacity"]');await click(page,'[data-gate-pass="risk"]');await click(page,'[data-gate-pass="rollback"]');
  await click(page,'#toLaunchDecision');
  if(delay){for(const id of ['checkpoint','stability'])if(await page.locator(`[data-extra-check="${id}"]`).count())await click(page,`[data-extra-check="${id}"]`);if(await page.locator('#delayLaunch').count())await click(page,'#delayLaunch');else await click(page,'#launchReady');}
  else if(await page.locator('#criticalOnly').count())await click(page,'#criticalOnly');else await click(page,'#launchReady');
}
async function completeFailover(page){for(const index of [0,1,2])await click(page,`[data-failover-check="${index}"]`);await page.getByText(/1\/3 حالات يمكن امتصاصها/).waitFor({state:'visible'});await click(page,'#finishFailover');if(await page.locator('#finishFailover').count())await click(page,'#finishFailover');}
async function completeTransfer(page){for(const [id,value] of Object.entries({weights:'build',retrieval:'request',inference:'request',monitoring:'continuous',maintenance:'continuous'}))await page.selectOption(`[data-transfer-item="${id}"]`,value);await click(page,'#transferSubmit');}
function advancedFlags(extra={}){return{dataIndex:1,dataStatuses:['ready'],dataChecks:[{rights:'clear',privacy:'clear',fitness:'clear'}],dataSort:{keep:1,remove:0,redact:0,review:0},dataTrainingUsed:[0],dataCurrentTrainingUsed:[0],candidateRevision:1,trainingIncidentChoice:'pause',evalIndex:3,evalCorrectCount:3,evaluatorCalibrationComplete:true,checkpointEvalComplete:true,safetyChoice:'details',safetyRemediated:true,safetyRetested:true,...extra};}

async function runJourney(viewport,label){
  console.log(`SMOKE_PHASE:${label}:start`);
  const browser=await chromium.launch(),page=await browser.newPage({viewport}),errors=[];page.on('pageerror',error=>errors.push(error.stack||error.message));await load(page);
  await click(page,'#introSend');await click(page,'#descend');await click(page,'#chapterNext');await click(page,'#startMine');
  await click(page,'[data-sector="b"]');await click(page,'[data-sector="b"]');await click(page,'#mineStop');await click(page,'#finishMine');for(let i=0;i<4;i+=1)await click(page,'[data-sector="b"]');await click(page,'#mineAbstract');await click(page,'#abstractNext');
  await click(page,'#chapterNext');await click(page,'#enterFab');await click(page,'#observeFab');await click(page,'#fabContinue');await click(page,'#startFactoryMaintenance');await click(page,'#diagnoseFactory');await click(page,'#verifyFactoryRepair');await click(page,'#toFactoryAbstract');await click(page,'#abstractNext');
  await click(page,'#chapterNext');for(const step of ['rack','network','power','register'])await click(page,`[data-server-step="${step}"]`);await click(page,'#bootServer');await click(page,'#dcMove');await click(page,'#repairCooling');await click(page,'#dcAfterCooling');await click(page,'#dcReady');await click(page,'#abstractNext');
  await click(page,'#chapterNext');await click(page,'#toClean');await chooseData(page,'remove');await chooseData(page,'keep');await chooseData(page,'review');await click(page,'#followupRedact');await chooseData(page,'review');await chooseData(page,'review');await click(page,'#dataAbstract');await click(page,'#abstractNext');
  await click(page,'#chapterNext');await click(page,'#startAnnot');for(const choice of ['آمن','عنف','مضايقة أو إساءة'])await chooseAnnotation(page,choice);await click(page,'#takeBreak');for(const choice of ['غير واضح','خطاب كراهية','غير واضح'])await chooseAnnotation(page,choice);if(await page.locator('#appeal').count())await click(page,'#appeal');await click(page,'#annotAbstract');await click(page,'#abstractNext');
  await click(page,'#chapterNext');if(await page.locator('#computeSel').count())throw new Error(`${label}: obsolete compute selector still exists.`);await page.selectOption('#checkpointSel','recent');await click(page,'#trainStart');let state=await saved(page);if(Object.hasOwn(state.flags,'trainingCompute'))throw new Error(`${label}: obsolete trainingCompute persisted in schema v6.`);if(!state.decisions.some(decision=>decision.id===`training-compute-8-r${state.flags.candidateRevision}`))throw new Error(`${label}: fixed 8-group training constraint was not recorded.`);await click(page,'#trainContinue');await click(page,'#sendHuman');await click(page,'#abstractNext');
  await click(page,'#chapterNext');for(const choice of ['a','b','bad']){if(choice==='b')await page.getByText(DEMO_PROMPT,{exact:true}).waitFor({state:'visible'});await click(page,`[data-eval="${choice}"]`);await click(page,'#nextEval');}if(await page.locator('#calibrationChoice').count())await page.selectOption('#calibrationChoice','a');await click(page,'#confirmCalibration');await completeCheckpoint(page);await click(page,'[data-safety="details"]');await click(page,'#remediateSafety');await click(page,'#confirmSafetyRetest');await completeRelease(page,{delay:true});await click(page,'#finishEval');await click(page,'#abstractNext');
  await click(page,'#chapterNext');await setLoad(page,[45,30,25]);await click(page,'#testLoad');await completeFailover(page);for(const tab of ['network','compute','model'])await click(page,`[data-tab="${tab}"]`);await click(page,'#rollback');await page.locator('#verifyRecovery').waitFor({state:'visible'});await click(page,'#verifyRecovery');await click(page,'#toSupport');await click(page,'#supportInvestigate');await click(page,'#supportFast');await click(page,'#uptimeAbstract');await click(page,'#abstractNext');
  await click(page,'#backPrompt');await page.getByText('وقد يحدث وقت الطلب بحسب تصميم المنتج',{exact:true}).waitFor({state:'visible'});await click(page,'#transferFromAnswer');await completeTransfer(page);await click(page,'#transferContinue');state=await saved(page);const displayed=await page.locator('.full-evidence-details .decision-row').count();if(displayed!==state.decisions.length)throw new Error(`${label}: full record displays ${displayed}/${state.decisions.length}.`);await page.getByRole('heading',{name:'سلسلة استخدام البيانات عبر النسخ',exact:true}).waitFor({state:'visible'});await page.getByRole('heading',{name:'الواجهة هي نهاية السلسلة، وليست بدايتها.',exact:true}).waitFor({state:'visible'});if(await page.locator('#toFinalMessage').count())throw new Error(`${label}: redundant final message route still exposed.`);if(errors.length)throw new Error(`${label}: page errors: ${errors.join(' | ')}`);await browser.close();console.log(`Complete journey passed: ${label}`);
}

async function runCausalChecks(){
  console.log('SMOKE_PHASE:causal');const browser=await chromium.launch(),page=await browser.newPage({viewport:{width:1280,height:900}});
  await load(page,{scene:'trainingSetup',flags:{dataIndex:1,dataStatuses:['excluded'],dataChecks:[{rights:'na',privacy:'na',fitness:'na'}],dataSort:{keep:0,remove:1,redact:0,review:0}}});if(!(await page.locator('#trainStart').isDisabled()))throw new Error('Training started with zero eligible inputs.');
  await load(page,{scene:'dataClean',flags:{dataIndex:1,dataStatuses:['ready'],dataChecks:[{rights:'clear',privacy:'clear',fitness:'clear'}],dataSort:{keep:1,remove:0,redact:0,review:0}}});await chooseData(page,'review');let state=await saved(page);if(state.flags.dataStatuses[1]!=='pending'||Object.values(state.flags.dataChecks[1]).some(value=>value!=='clear'))throw new Error('Review changed known clean evidence instead of route status only.');
  await load(page,{scene:'dcCooling',flags:{serverSteps:['rack','power','network','register']}});await click(page,'#dcStop');state=await saved(page);if(state.flags.dcCoolingChoice!=='stop'||state.flags.dcCoolingRestored)throw new Error('Stopping the datacenter test did not preserve an explicit unresolved stop state.');await page.locator('#repairCooling').waitFor({state:'visible'});await click(page,'#repairCooling');state=await saved(page);if(!state.flags.dcCoolingRestored||state.flags.dcCoolingChoice!=='stop')throw new Error('Explicit cooling repair did not close stop path.');
  await load(page,{scene:'factoryIncident'});await click(page,'#fabStop');state=await saved(page);if(!state.flags.factoryMaintenanceDebt||state.flags.factoryRemediationStage!=='none')throw new Error('Factory stop completed remediation automatically.');await click(page,'#diagnoseFactory');state=await saved(page);if(state.flags.factoryRemediationStage!=='diagnosed'||!state.flags.factoryMaintenanceDebt)throw new Error('Factory diagnosis did not remain separate from repair.');await click(page,'#verifyFactoryRepair');state=await saved(page);if(state.flags.factoryRemediationStage!=='verified'||state.flags.factoryMaintenanceDebt)throw new Error('Factory repair verification did not close maintenance debt.');
  await load(page,{scene:'releaseGateReview',flags:{...advancedFlags({releaseGates:[]})}});await click(page,'[data-gate-investigate="capacity"]');await page.waitForTimeout(50);if(await page.evaluate(()=>document.activeElement?.tagName)!=='H1')throw new Error('Same-scene rerender lost focus.');
  await load(page,{scene:'deployMonitoring',decisions:[{id:'deploy-resilience-risk-45-30-25',label:'قبول قيد',effectText:'fixture'}],flags:{...advancedFlags({trainingCheckpoint:'recent',releaseGates:['regression','capacity','risk','rollback'],launchChoice:'fast',deferredExtraChecks:['checkpoint'],deployLoad:[45,30,25],deployFailoverChecks:[0,1,2]})}});await page.getByRole('heading',{name:'فُتحت حركة المستخدمين مع دين تحقق مسجل.',exact:true}).waitFor({state:'visible'});await click(page,'#openMonitoringWindow');await click(page,'[data-monitoring-check="checkpoint"]');state=await saved(page);if(!state.flags.monitoringChecksCompleted.includes('checkpoint'))throw new Error('Deferred monitoring work was not persisted.');await click(page,'#finishMonitoring');
  await load(page,{scene:'onCall',flags:{...advancedFlags({releaseGates:['regression','capacity','risk','rollback'],launchChoice:'ready',deployLoad:[45,30,25],deployFailoverChecks:[0,1,2],deployTabs:['network','compute','model'],deployRecovery:'rollback'})},decisions:[{id:'deploy-resilience-risk-45-30-25',label:'قبول قيد',effectText:'fixture'}]});if(await page.locator('#toSupport').count())throw new Error('Support opened before recovery verification.');await click(page,'#verifyRecovery');await page.locator('#toSupport').waitFor({state:'visible'});
  await load(page,{scene:'onCall',flags:{...advancedFlags({releaseGates:['regression','capacity','risk','rollback'],launchChoice:'ready',deployLoad:[45,30,25],deployFailoverChecks:[0,1,2],deployTabs:['network','compute','model'],deployRecovery:'restart'})},decisions:[{id:'deploy-resilience-risk-45-30-25',label:'قبول قيد',effectText:'fixture'}]});await click(page,'#verifyRecovery');if(await page.locator('#toSupport').count())throw new Error('Restart verification was treated as root-cause closure.');await click(page,'#monitorRelease');state=await saved(page);if(state.flags.deployRecoveryDisposition!=='monitor')throw new Error('Restart residual risk was not recorded as operational debt.');await page.locator('#toSupport').waitFor({state:'visible'});
  await browser.close();console.log('Causal checks passed.');
}

async function runMigrationBrowserCheck(){console.log('SMOKE_PHASE:migration');const browser=await chromium.launch(),page=await browser.newPage({viewport:{width:1280,height:900}}),v3=clone(DEFAULT_STATE);v3.schemaVersion=3;for(const key of ['dataTrainingApproved','dataCurrentTrainingUsed','candidateRevision','evaluatorCalibrationComplete','deferredExtraChecks','monitoringChecksCompleted','factoryRemediationStage','deployRecoveryDisposition'])delete v3.flags[key];v3.scene='finalAnswer';v3.flags.dataIndex=2;v3.flags.dataStatuses=['excluded','ready'];v3.flags.dataChecks=[{rights:'na',privacy:'na',fitness:'na'},{rights:'clear',privacy:'clear',fitness:'clear'}];v3.flags.dataSort={keep:1,remove:1,redact:0,review:0};v3.flags.trainingCompute='12';await page.goto(BASE_URL,{waitUntil:'networkidle'});await page.evaluate(({key,value})=>{localStorage.clear();localStorage.setItem(key,JSON.stringify(value));},{key:STORAGE_KEY,value:v3});await page.reload({waitUntil:'networkidle'});const migrated=await saved(page);if(migrated.schemaVersion!==6||migrated.scene!=='trainingSetup'||Object.hasOwn(migrated.flags,'trainingCompute'))throw new Error('Browser v3 migration did not rewind safely into schema v6.');const invalid=currentState({scene:'finalMessage'});await page.evaluate(({key,value})=>localStorage.setItem(key,JSON.stringify(value)),{key:STORAGE_KEY,value:invalid});await page.reload({waitUntil:'networkidle'});if((await saved(page)).scene!=='intro')throw new Error('Removed finalMessage scene was accepted.');await browser.close();console.log('Browser migration and removed-scene reset passed.');}

async function runA11y(){console.log('SMOKE_PHASE:axe');const browser=await chromium.launch(),context=await browser.newContext({viewport:{width:1280,height:900}}),page=await context.newPage();const cases=[{scene:'intro'},{scene:'trainingSetup',flags:{dataIndex:1,dataStatuses:['excluded'],dataChecks:[{rights:'na',privacy:'na',fitness:'na'}],dataSort:{keep:0,remove:1,redact:0,review:0}}},{scene:'checkpointEval',flags:{...advancedFlags({checkpointEvalComplete:false})}},{scene:'releaseGateReview',flags:{...advancedFlags({releaseGates:[]})}},{scene:'deployLoad',flags:{...advancedFlags({releaseGates:['regression','capacity','risk','rollback'],launchChoice:'ready'})}}];for(const patch of cases){await load(page,patch);const results=await new AxeBuilder({page}).analyze(),serious=results.violations.filter(item=>['serious','critical'].includes(item.impact));if(serious.length)throw new Error(`Accessibility violations in ${patch.scene}: ${serious.map(item=>item.id).join(', ')}`);}await context.close();await browser.close();console.log('Dynamic accessibility matrix passed.');}
async function crossBrowser(browserType,label){const browser=await browserType.launch(),page=await browser.newPage({viewport:{width:390,height:844}});await load(page);await click(page,'#settingsBtn');await page.locator('#settingsDialog').waitFor({state:'visible'});await click(page,'#settingsDialog [data-close-dialog]');await click(page,'#introSend');await click(page,'#descend');await page.getByRole('heading',{name:'استخراج مواد الأجهزة',exact:true}).waitFor({state:'visible'});await browser.close();console.log(`${label} smoke passed.`);}

await runJourney({width:1280,height:900},'desktop');
await runJourney({width:390,height:844},'mobile');
await runCausalChecks();
await runMigrationBrowserCheck();
await runA11y();
await crossBrowser(firefox,'firefox');
await crossBrowser(webkit,'webkit');
console.log('Browser v6 journey, tenth-audit causality, migration, accessibility and cross-browser checks passed.');
