function miniMap(ctx,index){return ctx.chapters.map((c,i)=>`<span class="mini-node ${i===index?'current':i<index?'done':''}" title="${ctx.h(c.title)}"><span>${c.icon}</span><small>${ctx.h(c.shortTitle||c.title)}</small></span>`).join('');}

export function setChapter(ctx,index){const {state,progressEl,ledgerBtn,persistentFooter,chapterLabel,chapterTitle,progressFill,chapters,saveState}=ctx;state.chapter=index;const mini=ctx.$('#miniJourney');if(index>=0){progressEl.hidden=false;ledgerBtn.hidden=false;persistentFooter.hidden=false;chapterLabel.textContent=`المرحلة ${index+1} من 9`;chapterTitle.textContent=chapters[index]?.shortTitle||chapters[index]?.title||'';progressFill.style.width=`${((index+1)/9)*100}%`;if(mini)mini.innerHTML=miniMap(ctx,index);}else{progressEl.hidden=true;ledgerBtn.hidden=true;persistentFooter.hidden=true;if(mini)mini.innerHTML='';}saveState();}

function journeyMap(ctx,index){return `<div class="journey-map" aria-label="خريطة رحلة الإجابة">${ctx.chapters.map((c,i)=>`<div class="journey-node ${i===index?'current':i<index?'done':''}"><span class="journey-icon">${c.icon}</span><small>${ctx.h(c.shortTitle||c.title)}</small></div>`).join('')}</div>`;}

function terminology(index){if(index===1)return `<div class="learning-card term-card"><h3>مصطلح سنستخدمه لاحقًا: النموذج</h3><p>المقصود بـ«النموذج» البرنامج الرياضي الذي يتعلم أنماطًا من كميات كبيرة من البيانات ثم يستخدم ما تعلمه لإنتاج إجابات جديدة.</p></div>`;if(index===2)return `<div class="learning-card term-card"><h3>ما هو الخادم؟</h3><p>الخادم حاسوب قوي مخصص لتشغيل خدمات وبرامج باستمرار. توجد أعداد كبيرة من هذه الأجهزة داخل مراكز البيانات.</p></div>`;if(index===5)return `<div class="learning-card term-card"><h3>ما معنى تدريب النموذج؟</h3><p>هي العملية التي تُعرض فيها أمثلة كثيرة على النموذج وتُعدَّل قيمه الداخلية تدريجيًا حتى يتحسن في توقع الأنماط وإنتاج النص.</p></div>`;return '';}

export function chapterIntro(ctx,index,_title,_subtitle,next){const c=ctx.chapters[index];ctx.setChapter(index);ctx.html(`<div class="learning-intro"><div><span class="chapter-theme">${c.icon} المرحلة ${index+1} من 9</span><h1 class="display-title">${ctx.h(c.title)}</h1><p class="scene-subtitle">لا تحتاج إلى معرفة هذه المرحلة مسبقًا. سنبني الرابط بينها وبين الإجابة خطوة بخطوة.</p></div>${journeyMap(ctx,index)}${terminology(index)}<div class="learning-grid"><div class="learning-card"><h3>أين نحن؟</h3><p>${ctx.h(c.where)}</p></div><div class="learning-card"><h3>ماذا يحدث هنا؟</h3><p>${ctx.h(c.what)}</p></div><div class="learning-card"><h3>ما علاقتها بالذكاء الاصطناعي؟</h3><p>${ctx.h(c.link)}</p></div><div class="learning-card"><h3>من يعمل هنا؟</h3><p>${ctx.h(c.workers)}</p></div></div><details class="reality-note"><summary><strong>أين يحدث هذا في الواقع؟</strong></summary><p>${ctx.h(c.where)} ${ctx.h(c.workers)} تختلف الشركات والبلدان والتقنيات من سلسلة إلى أخرى، لذلك تمثل اللعبة نوع المرحلة لا موردًا أو شركة بعينها.</p></details><div class="journey-link"><strong>اربطها بطلبك:</strong> إجابتك ما زالت تنتظر. هذه المرحلة تبني شيئًا تحتاجه المراحل التالية قبل أن تصل إلى مربع المحادثة.</div><div class="stage-output"><strong>ما الذي سنخرج به من هذه المرحلة؟</strong>${ctx.h(c.output)}</div><div class="action-row"><button id="chapterNext" class="primary-btn">ابدأ هذه المرحلة</button></div></div>`);ctx.$('#chapterNext').addEventListener('click',()=>ctx.go(next));}
